// <auto-generated />
using System;
using CovidDailyCases.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CovidDailyCases.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CovidCasesDbContext))]
    [Migration("20221220164335_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CovidDailyCases.Domain.Models.CovidCases", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("NumSequences")
                        .HasColumnType("integer");

                    b.Property<int>("NumSequencesTotal")
                        .HasColumnType("integer");

                    b.Property<double>("PercSequences")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CovidCases");
                });
#pragma warning restore 612, 618
        }
    }
}
