version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: covid123456
    ports:
        - "5432:5432"

   
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "lukssob@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "covid123456"
    ports:
      - "16543:80"